"""new tables 

Revision ID: b09f222c23e7
Revises: 
Create Date: 2018-12-06 02:01:44.056038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b09f222c23e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fullname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('xray', sa.Text(), nullable=True),
    sa.Column('tablets', sa.Text(), nullable=True),
    sa.Column('bandage', sa.Text(), nullable=True),
    sa.Column('appoinments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('bills')
    # ### end Alembic commands ###
